//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//


import Foundation
import Combine

protocol ___VARIABLE_moduleName___ViewModelProtocol {
    
}

final class ___VARIABLE_moduleName___ViewModel:ObservableObject {    
    init() {
    }
}

// MARK: - ___VARIABLE_moduleName___ViewModelProtocol
extension ___VARIABLE_moduleName___ViewModel: ___VARIABLE_moduleName___ViewModelProtocol {
    
}
